apiVersion: 1
datasources:
  - name: InfluxDB
    uid: loginlogbook-influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: loginlogbook
      defaultBucket: logins
    secureJsonData:
      token: ${INFLUX_TOKEN}
    isDefault: true
    editable: false
