import system from 'system';
import { report, runAll } from './harness.js';
import './metadata.test.js';
import './config.test.js';
import './models.test.js';
import './store.test.js';
import './net.test.js';
import './i18n.test.js';
import './locale_parity.test.js';
import './enforcement.test.js';
import './helpers.test.js';
import './stylesheet.test.js';
import './time.test.js';
await runAll();
system.exit(report());
